version: 2

sources:
    - name: purchasing
      description: 'Lista dos fornecedores.'
      schema: purchasing
      tables:
      - name: vendor
        columns:
          - name: businessentityid
            description: "Número de identificação de cada fornecedor."
            tests:
              - unique
              - not_null
          - name: accountnumber
            description: "Número da conta do fornecedor."
            tests:
              - unique
              - not_null
          - name: name
            description: "Nome do fornecedor."
            tests:
              - not_null
          - name: preferredvendorstatus
            description: "Preferência pelo fornecedor para fornecimento de um determinado produto, true = preferido, false = usar outro fornecedor."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."


      - name: dim_date
        description: "Tabela de dimensão de data. Derivada da seed."
      - name: shipmethod
        columns:
          - name: shipmethodid
            description: "Número de identificação da empresa transportadora."
            tests:
              - unique
              - not_null
          - name: name
            description: "Nome da empresa transportadora."
            tests:
              - unique
              - not_null
          - name: shipbase
            description: "Custo mínimo de envio."
            tests:
              - not_null
          - name: shiprate
            description: "Custo de envio por peso."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null


      - name: productvendor
        columns:
          - name: productid
            description: "Número de identificação do produto."
            tests:
              - not_null
          - name: businessentityid
            description: "Número de identificação do fornecedor."
            tests:
              - not_null
          - name: averageleadtime
            description: "O intervalo médio de tempo (em dias) entre a realização de um pedido ao fornecedor e o recebimento do produto adquirido."
            tests:
              - not_null
          - name: standardprice
            description: "O preço de venda normal do fornecedor."
            tests:
              - not_null
          - name: lastreceiptcost
            description: "O preço de venda na última compra."
            tests:
              - not_null
          - name: lastreceiptdate
            description: "Data em que o produto foi recebido pela última vez pelo fornecedor."
            tests:
              - not_null
          - name: minorderqty
            description: "A quantidade mínima que deve ser solicitada."
            tests:
              - not_null
          - name: maxorderqty
            description: "A quantidade máxima que deve ser solicitada."
            tests:
              - not_null
          - name: onorderqty
            description: "A quantidade atualmente em pedido."
          - name: unitmeasurecode
            description: "Unidade de medida do produto."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null


      - name: purchaseorderdetail
        columns:
          - name: purchaseorderid
            description: "Número de identificação da compra"
            tests:
              - not_null
          - name: purchaseorderdetailid
            description: "Número de identificação de cada produto da compra."
            tests:
              - unique
              - not_null
          - name: productid
            description: "Número de identificação do produto."
            tests:
              - not_null
          - name: unitprice
            description: "Preço de venda do fornecedor de um único produto."
            tests:
              - not_null
          - name: orderqty
            description: "Quantidade encomendada."
            tests:
              - not_null
          - name: receivedqty
            description: "Quantidade efetivamente recebida do fornecedor."
            tests:
              - not_null
          - name: rejectedqty
            description: "Quantidade rejeitada durante a inspeção."
            tests:
              - not_null
          - name: duedate
            description: "Data prevista para o recebimento do produto."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null



      - name: purchaseorderheader
        columns:
          - name: purchaseorderid
            description: "Número identificador da encomenda."
            tests:
              - unique
              - not_null
          - name: status
            description: "Status atual da encomenda."
            tests:
              - not_null
          - name: shipdate
            description: "Data estimada de envio do fornecedor."
            tests:
              - not_null
          - name: orderdate
            description: "Data de criação do pedido de compra."
            tests:
              - not_null
          - name: taxamt
            description: "Valor do imposto."
            tests:
              - not_null
          - name: freight
            description: "Valor da entrega."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null


    - name: production
      description: "Tabela de dimensão de produção"
      schema: production
      tables:
      - name: product
        columns:
          - name: productid
            description: "Número identificador do produto."
            tests:
              - unique
              - not_null
          - name: name
            description: "Nome do produto."
            tests:
              - not_null
          - name: productnumber
            description: "Identificação do produto."
            tests:
              - unique
              - not_null
          - name: makeflag
            description: "Identifica se o produto foi comprado ou fabricado internamente. true = Produto comprado, false = Produto fabricado internamente."
            tests:
              - not_null
          - name: safetystocklevel
            description: "Quantidade mínima de stock."
            tests:
              - not_null
          - name: reorderpoint
            description: "Nível de inventário que quando atingido é preciso encomendar novo stock."
            tests:
              - not_null
          - name: standardcost
            description: "Custo de produção."
            tests:
              - not_null
          - name: listprice
            description: "Preço de venda do produto."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null


    - name: person
      description: 'Lista dos empregados da Advworks.'
      schema: person
      tables:
      - name: person
        columns:
          - name: businessentityid
            description: "Identificador do empregado."
            tests:
              - unique
              - not_null
          - name: firstname
            description: "Primeiro nome do empregado."
            tests:
              - not_null
          - name: middlename
            description: "Nome do meio do empregado."
          - name: lastname
            description: "Apelido do empregado."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null

      - name: emailaddress
        columns:
          - name: businessentityid
            description: "Identificador do empregado."
            tests:
              - unique
              - not_null
          - name: emailaddress
            description: "Email do empregado."
            tests:
              - unique
              - not_null

      - name: businessentity
        columns:
          - name: businessentityid
            description: "Identificador do empregado."
            tests:
              - unique
              - not_null


    - name: humanresources
      description: 'Lista dos empregados da Advworks.'
      schema: humanresources
      tables:
      - name: employee
        columns:
          - name: businessentityid
            description: "Identificador do empregado."
            tests:
              - unique
              - not_null
          - name: loginid
            description: "Identificador de login do empregado. Atualmente os valores são únicos."
            tests:
              - unique
              - not_null
          - name: nationalidnumber
            description: "Número de identificação nacional do empregado."
            tests:
              - unique
              - not_null
          - name: jobtitle
            description: "Título do cargo do empregado."
            tests:
              - not_null
          - name: organizationnode
            description: "Nó da organização do empregado."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."
            tests:
              - not_null

      - name: employeedepartmenthistory
        columns:
          - name: businessentityid
            description: "Identificador do empregado."
            tests:
              - not_null
          - name: departmentid
            description: "Identificador  do departamento do empregado."
            tests:
              - not_null
          - name: modifieddate
            description: "Data da última atualização da linha."

      - name: department
        columns:
          - name: departmentid
            description: "Identificador do departamento do empregado."
            tests:
              - unique
              - not_null
          - name: name
            description: "Nome do departamento."
            tests:
              - unique
              - not_null


models:
  - name: dim_vendor
    columns:
      - name: sk_vendor
        description: "Chave suplementar para a dimensão do fornecedor."
        tests:
          - unique
          - not_null
      - name: vendor_id
        description: "Identificador do fornecedor."
        tests:
          - unique
          - not_null
      - name: account_number
        description: "Número de conta associado ao fornecedor."
        tests:
          - unique
          - not_null
      - name: vendor_name
        description: "Nome do fornecedor."
        tests:
          - not_null
      - name: preferred_vendor_status
        description: "Estado que indica se o fornecedor é preferido ou não."
        tests:
          - not_null
      - name: valid_from
        description: "Data de início de validade do registo na dimensão."
      - name: valid_to
        description: "Data de término de validade do registo na dimensão."
      - name: last_updated_at
        description: "Timestamp indicando quando o registo foi atualizado pela última vez."
    meta:
      dbt_updated_at: true


  - name: dim_employee
    columns:
      - name: sk_employee
        description: "Chave suplementar para a dimensão do empregado."
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "Identificador do empregado."
        tests:
          - unique
          - not_null
      - name: national_nr_id
        description: "Número de identificação nacional do empregado."
        tests:
          - unique
          - not_null
      - name: login_id
        description: "Identificador de login do empregado."
        tests:
          - not_null
      - name: first_name
        description: "Primeiro nome do empregado."
        tests:
          - not_null
      - name: middle_name
        description: "Nome do meio do empregado."
      - name: last_name
        description: "Último nome do empregado."
        tests:
          - not_null
      - name: email
        description: "Endereço de e-mail do empregado."
        tests:
          - not_null
      - name: department_name
        description: "Nome do departamento onde o empregado trabalha."
        tests:
          - not_null
      - name: job_title
        description: "Título do cargo do empregado."
        tests:
          - not_null
      - name: organization_node
        description: "Nó da organização do empregado."
      - name: valid_from
        description: "Data de início de validade do registo na dimensão."
      - name: valid_to
        description: "Data de término de validade do registo na dimensão."
      - name: last_updated_at
        description: "Timestamp indicando quando o registo foi atualizado pela última vez."
    meta:
      dbt_updated_at: true


  - name: dim_shipment
    columns:
      - name: sk_shipmethod
        description: "Chave suplementar para a dimensão do método de envio."
        tests:
          - unique
          - not_null
      - name: shipmethod_id
        description: "Identificador do método de envio."
        tests:
          - unique
          - not_null
      - name: company_name
        description: "Nome da empresa de envio."
        tests:
          - unique
          - not_null
      - name: ship_base
        description: "Taxa base de envio."
        tests:
          - not_null
      - name: ship_rate
        description: "Taxa de envio."
        tests:
          - not_null
      - name: valid_from
        description: "Data de início de validade do registo na dimensão."
      - name: valid_to
        description: "Data de término de validade do registo na dimensão."
      - name: last_updated_at
        description: "Timestamp indicando quando o registo foi atualizado pela última vez."
    meta:
      dbt_updated_at: true


  - name: fact_purchasing
    columns:
      - name: purchase_detail_id
        description: "Identificador do detalhe da compra."
        tests:
          - unique
          - not_null
      - name: vendor_name
        description: "Nome do fornecedor."
        tests:
          - not_null
      - name: product_name
        description: "Nome do produto."
        tests:
          - not_null
      - name: unit_price
        description: "Preço unitário."
        tests:
          - not_null
      - name: order_qty
        description: "Quantidade encomendada."
        tests:
          - not_null
      - name: received_qty
        description: "Quantidade recebida."
        tests:
          - not_null
      - name: rejected_qty
        description: "Quantidade rejeitada."
        tests:
          - not_null
      - name: purchase_order_id
        description: "Identificador da ordem de compra."
        tests:
          - not_null
      - name: employee_loginid
        description: "Login do funcionário."
        tests:
          - not_null
      - name: shipment
        description: "Envio."
        tests:
          - not_null
      - name: order_status
        description: "Estado da ordem."
        tests:
          - not_null
      - name: tax_amt
        description: "Valor do imposto."
        tests:
          - not_null
      - name: freight
        description: "Frete."
        tests:
          - not_null
      - name: ship_date
        description: "Data de envio."
        tests:
          - not_null
      - name: due_date
        description: "Data de vencimento."
        tests:
          - not_null
      - name: order_date
        description: "Data da ordem."
        tests:
          - not_null
      - name: purchasing_last_update
        description: "Data da última atualização do registo de compra."
        tests:
          - not_null